os: osx
osx_image:
  - xcode11.5
  - xcode11.4
  - xcode11.3
  - xcode11.2
  - xcode11.1
  - xcode11
  - xcode10.3
  - xcode10.2
  - xcode10.1
  - xcode10
  - xcode9.4
  - xcode9.3
  - xcode9.2
  - xcode9.1
  - xcode9
  - xcode8.3
  - xcode8
  - xcode7.3
  - xcode6.4
script:
  - python --version || true
  - pip --version || true
  - python3 --version || true
  - pip3 --version || true
  - /usr/sbin/softwareupdate --history | grep "Command Line Tools for Xcode"
